version: "3.1"

services:
  db:
    image: postgres
    container_name: db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:rw
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres-data-volume:
    name: postgres-storage-todo
    driver: local
