version: "3.1"

services:
  db:
    container_name: db-container
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGTZ=Asia/Tokyo
    volumes:
      - postgres-volume-todo:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
volumes:
  postgres-volume-todo:
